pacman_packages_remove=(
  1password-cli
  1password-beta
  kdenlive
  limine-snapper-sync
  signal-desktop
  xournalpp
  typora
  mako
  swayosd
  libreoffice-fresh
)

pacman_packages_install=(
  flatpak
  fish
  tmux
  ghostty
  7zip
  yazi
  btop
  tree
  tldr
  bat
  thefuck
  kew
  swaync
  nano
  cava
  go
  cpio
  cmake
  cmatrix
  stow
  lib32-mesa
  lib32-vulkan-intel
  vulkan-intel
  visual-studio-code-bin
  glow
  vhs
  skate
  shotwell
  zip
  unzip
  wget
  curl
  speedtest-cli
  vlc
  hyprshot
  ttf-firacode-nerd
  ttf-cascadia-code
  ttf-iosevka-nerd
)

yay_package_install=(
  vicinae-bin
  tty-clock
  crush-bin
  nautilus-backspace
  hyprmoncfg
  t3code-bin
  charm-pop-bin
)

flatpak_package_install=(
  com.github.neithern.g4music
  app.zen_browser.zen
  com.discordapp.Discord
  io.missioncenter.MissionCenter
  com.getpostman.Postman
  fr.handbrake.ghb
  dev.geopjr.Calligraphy
)

bun_package_install=(
  opencode-ai
  @google/gemini-cli
  @openai/codex
  @github/copilot
  git-open
  port-whisperer
)
